# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dnsadblock < Formula
  desc "DnsAdBlock DNS Proxy"
  homepage "https://dnsadblock.com"
  version "0.2.97"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/dnsadblock/proxy/releases/download/v0.2.97/dnsadblock_0.2.97_darwin_amd64.tar.gz"
    sha256 "7834dadc40410514d58d586d0b71ba4a232f82ee009b83c00eddfc2047e2da54"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/dnsadblock/proxy/releases/download/v0.2.97/dnsadblock_0.2.97_darwin_arm64.tar.gz"
    sha256 "db2289cec29877663e515347e7f7b4450709ba43595d40671e0345a44f791c41"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/dnsadblock/proxy/releases/download/v0.2.97/dnsadblock_0.2.97_linux_amd64.tar.gz"
    sha256 "653bd28d79c267588c9ead39bde7fc60df320ed6391cdbab7bb7ec92adb99bcd"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/dnsadblock/proxy/releases/download/v0.2.97/dnsadblock_0.2.97_linux_armv6.tar.gz"
    sha256 "f34e8dc8bbbc6483ddcc445d631c831873c31a284b077e4950913194e5133d9b"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/dnsadblock/proxy/releases/download/v0.2.97/dnsadblock_0.2.97_linux_arm64.tar.gz"
    sha256 "498652bcaa18b2e08c9594724f5684215f48fc8b4328686a828a2887df1ad6a7"
  end

  def install
    bin.install "dnsadblock"
  end

  def caveats; <<~EOS
    To install DnsAdBlock, run the following command: sudo dnsadblock install --config <your_conf_id> Then setup your DNS manually to 127.0.0.1 or by running: sudo dnsadblock activate
  EOS
  end
end
