# This file was generated by GoReleaser. DO NOT EDIT.
class Dnsadblock < Formula
  desc "dnsadblock DNS Proxy"
  homepage "https://dnsadblock.com"
  version "0.2.52"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/dnsadblock/proxy-release/releases/download/v0.2.52/dnsadblock_0.2.52_darwin_amd64.tar.gz"
    sha256 "969f48a881dd0a43fc478085137d4e4f56d9af98e91cc737c2045260d34b2f98"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/dnsadblock/proxy-release/releases/download/v0.2.52/dnsadblock_0.2.52_linux_amd64.tar.gz"
      sha256 "8e78d6fffb5fc5fd9249415a1c43f08555a4c381038c227736ce2dd6a29d6a1e"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dnsadblock/proxy-release/releases/download/v0.2.52/dnsadblock_0.2.52_linux_arm64.tar.gz"
        sha256 "29f51bcf0444fc69183965a5f997eb004ca74f5fd4bc21236e0e275f55817ac6"
      else
        url "https://github.com/dnsadblock/proxy-release/releases/download/v0.2.52/dnsadblock_0.2.52_linux_armv6.tar.gz"
        sha256 "8170794a7503287bd087ea1f126ee52e9250c6dc7ca1be65364f18c6e6537d02"
      end
    end
  end

  def install
    bin.install "dnsadblock"
  end

  def caveats; <<~EOS
    To install dnsadblock, run the following command:
    sudo dnsadblock install --config <your_conf_id>
    Then setup your DNS manually to 127.0.0.1 or by running:
    sudo dnsadblock activate
  EOS
  end
end
