# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dnsadblock < Formula
  desc "DnsAdBlock DNS Proxy"
  homepage "https://dnsadblock.com"
  version "0.2.166"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/dnsadblock/proxy-release/releases/download/v0.2.166/dnsadblock_0.2.166_darwin_amd64.tar.gz"
    sha256 "fe03904263dd33005e9d6adfcc4d63a25d24553877c9c508d866f04d7c7d0995"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/dnsadblock/proxy-release/releases/download/v0.2.166/dnsadblock_0.2.166_darwin_arm64.tar.gz"
    sha256 "befc60d15b711001a0ccebb2ec0a6a4f05d7baa12b14735e1fca42f6a184eee7"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/dnsadblock/proxy-release/releases/download/v0.2.166/dnsadblock_0.2.166_linux_amd64.tar.gz"
    sha256 "ae5eba3bc1ea25205a785cd939f9dc8390e2ab457a22ac4669ab1cf940e81cd5"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/dnsadblock/proxy-release/releases/download/v0.2.166/dnsadblock_0.2.166_linux_armv6.tar.gz"
    sha256 "1b773c712a2bd78b1a89d44480d5f774590f65aa46b813289c82ae2807c59c87"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/dnsadblock/proxy-release/releases/download/v0.2.166/dnsadblock_0.2.166_linux_arm64.tar.gz"
    sha256 "4b25b4df6f373800246c2c1fa4b265d5a34810997ed6591fb209f954ba0c7df7"
  end

  def install
    bin.install "dnsadblock"
  end

  def caveats; <<~EOS
    To install DnsAdBlock, run the following command: sudo dnsadblock install --config <your_conf_id> Then setup your DNS manually to 127.0.0.1 or by running: sudo dnsadblock activate
  EOS
  end
end
