# This file was generated by GoReleaser. DO NOT EDIT.
class Proxy < Formula
  desc "dnsadblock DNS Proxy"
  homepage "https://dnsadblock.com"
  version "0.2.33-beta.23"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/dnsadblock/proxy-release/releases/download/v0.2.33-beta.23/proxy_0.2.33-beta.23_darwin_amd64.tar.gz"
    sha256 "631f7d80ca29009f84a818f3f8fa557b9d460a69cc49f1f2f398aa19d94a3ce7"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/dnsadblock/proxy-release/releases/download/v0.2.33-beta.23/proxy_0.2.33-beta.23_linux_amd64.tar.gz"
      sha256 "313312607130e3a4d9a3a994e00fa1259f97654870cfc0fd4ec20eda87ccc7ba"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dnsadblock/proxy-release/releases/download/v0.2.33-beta.23/proxy_0.2.33-beta.23_linux_arm64.tar.gz"
        sha256 "6ea4bc8320055e7f63696516a40c47b6ed768c7047325d75580560482d2d2809"
      else
        url "https://github.com/dnsadblock/proxy-release/releases/download/v0.2.33-beta.23/proxy_0.2.33-beta.23_linux_armv6.tar.gz"
        sha256 "d3a37f892c4c4ac172deaa5d1b7804fca3022e70be1dac95a04b2bfa56e6cdb3"
      end
    end
  end

  def install
    bin.install "proxy"
  end

  def caveats; <<~EOS
    To install dnsadblock, run the following command:
    sudo dnsadblock install --config <your_conf_id>
    Then setup your DNS manually to 127.0.0.1 or by running:
    sudo dnsadblock activate
  EOS
  end
end
