# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ProxyRelease < Formula
  desc "DnsAdBlock DNS Proxy"
  homepage "https://dnsadblock.com"
  version "0.2.66"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/dnsadblock/proxy-release/releases/download/v0.2.66/proxy-release_0.2.66_darwin_amd64.tar.gz"
    sha256 "927da768350708286640a57193ff98754b1af0d1e3d8a81e74c1f4bf1df1f3fb"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/dnsadblock/proxy-release/releases/download/v0.2.66/proxy-release_0.2.66_darwin_arm64.tar.gz"
    sha256 "621327d3877b3789b910c4f4d6fba3a11e3a97cfc4bb4aef644ba182aefa9ea6"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/dnsadblock/proxy-release/releases/download/v0.2.66/proxy-release_0.2.66_linux_amd64.tar.gz"
    sha256 "d1d3f30a8b13b4314c0fe36823a9e1959393df32a41e6132837018c965059de8"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/dnsadblock/proxy-release/releases/download/v0.2.66/proxy-release_0.2.66_linux_armv6.tar.gz"
    sha256 "27090954591f59b5f9b032ab17c71d8ffcc46bb12a6085806de73c52aeabd165"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/dnsadblock/proxy-release/releases/download/v0.2.66/proxy-release_0.2.66_linux_arm64.tar.gz"
    sha256 "c6a7ea19f4d9af872bc63a9d9a87b59db49819f4eccd49a2fde14e4720e12fc4"
  end

  def install
    bin.install "proxy-release"
  end

  def caveats; <<~EOS
    To install DnsAdBlock, run the following command: sudo dnsadblock install --config <your_conf_id> Then setup your DNS manually to 127.0.0.1 or by running: sudo dnsadblock activate
  EOS
  end
end
