# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ProxyRelease < Formula
  desc "DnsAdBlock DNS Proxy"
  homepage "https://dnsadblock.com"
  version "0.2.67"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/dnsadblock/proxy-release/releases/download/v0.2.67/proxy-release_0.2.67_darwin_amd64.tar.gz"
    sha256 "e02b5d9fdf1076b85be49c3093026f877e25c468f15f21f32070913ae1316fe1"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/dnsadblock/proxy-release/releases/download/v0.2.67/proxy-release_0.2.67_darwin_arm64.tar.gz"
    sha256 "c13a7d9c005705e7658c77234b9254117fcad6dc4fc4bd3d9cbf45872b4a2ad8"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/dnsadblock/proxy-release/releases/download/v0.2.67/proxy-release_0.2.67_linux_amd64.tar.gz"
    sha256 "4c1b5065161170d10ad90d8dcf5aec5d44121d1706e1a4dc1927d435c43d6341"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/dnsadblock/proxy-release/releases/download/v0.2.67/proxy-release_0.2.67_linux_armv6.tar.gz"
    sha256 "3109fa07133713c2726011b1c1e0d624abeb9cc7f6edf895f661843136e30b33"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/dnsadblock/proxy-release/releases/download/v0.2.67/proxy-release_0.2.67_linux_arm64.tar.gz"
    sha256 "c37f32d724cadf2c3a2b2b343b2cfe774803839f24f0c20905d727c2ef9f7c6e"
  end

  def install
    bin.install "proxy-release"
  end

  def caveats; <<~EOS
    To install DnsAdBlock, run the following command: sudo dnsadblock install --config <your_conf_id> Then setup your DNS manually to 127.0.0.1 or by running: sudo dnsadblock activate
  EOS
  end
end
