# This file was generated by GoReleaser. DO NOT EDIT.
class Proxy < Formula
  desc "dnsadblock DNS Proxy"
  homepage "https://dnsadblock.com"
  version "0.2.33-beta.18"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/dnsadblock/proxy-release/releases/download/v0.2.33-beta.18/proxy_0.2.33-beta.18_darwin_amd64.tar.gz"
    sha256 "9da075c8620bcf13903bd751b63b09bdf2de5cb076a11b4fdcf5cff343166811"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/dnsadblock/proxy-release/releases/download/v0.2.33-beta.18/proxy_0.2.33-beta.18_linux_amd64.tar.gz"
      sha256 "61ed73a805708fba5868f2f83315a072bca920ce41f693479644097dae205050"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dnsadblock/proxy-release/releases/download/v0.2.33-beta.18/proxy_0.2.33-beta.18_linux_arm64.tar.gz"
        sha256 "6617e6f00391186956e6e2dfe58a737e41b81f5005a65a5eb5b32b6dcff003dc"
      else
        url "https://github.com/dnsadblock/proxy-release/releases/download/v0.2.33-beta.18/proxy_0.2.33-beta.18_linux_armv6.tar.gz"
        sha256 "48f6cb4fab5aac65316cbad7be2249ed7febff10852ae3846c13091c5e103c55"
      end
    end
  end

  def install
    bin.install "proxy"
  end

  def caveats; <<~EOS
    To install dnsadblock, run the following command:
    sudo dnsadblock install --config <your_conf_id>
    Then setup your DNS manually to 127.0.0.1 or by running:
    sudo dnsadblock activate
  EOS
  end
end
